import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

import Header from './components/Header';
import Hero from './components/Hero'
import Stacks from './components/Stacks'

export default function Home() {
  return (
    <>
      <Head>
        <title>João Pedro Batista | Desenvolvedor Full-Stack</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/fav.png" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet" />
      </Head>

      <Header></Header>
      <Hero></Hero>
      <Stacks></Stacks>

    </>
  )
}
